# ~/.config/kitty/startup.conf
# Launch tabs
## Tab 1 | zsh
new_tab zsh
launch --title='kitty | zsh' /opt/homebrew/opt/zsh/bin/zsh -cil 'cd $HOME && cls && exec zsh'

## Tab 2 | undergrad
new_tab undergrad
launch --title='kitty | undergrad' /opt/homebrew/opt/zsh/bin/zsh -cil 'ko $UNDERGRADUATE && exec zsh'

## Tab 3 | frwyslnd.latex
new_tab frwyslnd.latex
launch --title='kitty | frwyslnd' /opt/homebrew/opt/zsh/bin/zsh -cil 'ko $LATEX_FRWYSLND && exec zsh'

## Tab 4 | frwyslnd.math
new_tab frwyslnd.math
launch --title='kitty | frwyslnd' /opt/homebrew/opt/zsh/bin/zsh -cil 'ko $FRWYSLND_MATH && exec zsh'

## Tab 5 | configs
new_tab configs
launch --title='kitty | configs' /opt/homebrew/opt/zsh/bin/zsh -cil 'ko $CONFIGURATIONS && exec zsh'

## Tab 6 | nvim
new_tab nvim
launch --title='kitty | nvim' /opt/homebrew/opt/zsh/bin/zsh -cil 'ko $NVIM_CONFIG_DIR && exec zsh'
