#!/usr/bin/env zsh
# ~/.config/zsh/functions/brew

# Dependencies
## Homebrew | https://brew.sh/

# Definition
brew () {
  if [ "$HAS_HOMEBREW_SHELLENV_BEEN_EVALUATED" = false ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
    HAS_HOMEBREW_SHELLENV_BEEN_EVALUATED=true
  fi

  /opt/homebrew/bin/brew "$@"
}
