#!/usr/bin/env zsh
# ~/.config/zsh/functions/brew

# Dependencies
## Homebrew | https://brew.sh/

# Definition
brew () {
  if [ -z "$HAS_HOMEBREW_SHELLENV_BEEN_EVALUATED" ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
    export HAS_HOMEBREW_SHELLENV_BEEN_EVALUATED='true'
  fi

  /opt/homebrew/bin/brew "$@"
}
