#!/usr/bin/env zsh
# ~/.config/zsh/functions/find_git_repositories
## Source: https://stackoverflow.com/a/4319315
find_git_repositories () {
  print -P %F{green}
  find ~/.config -type d -name .git -print && find ~/Configurations -type d -name .git -print && find ~/Projects -type d -name .git -print
}
