#!/usr/bin/env zsh
# ~/.zsh_functions/find_git_repositories
## Source: https://stackoverflow.com/a/4319315
find_git_repositories () {
  find ~/.config -type d -name .git -print && find ~/Configurations -type d -name .git -print && find ~/Projects -type d -name .git -print
}
