#!/usr/bin/env zsh
# ~/.config/zsh/functions/git_squash
## Source: https://stackoverflow.com/a/5201642/19821277
## Syntax:
## git_squash <nth_last_commit> <commit_message_title> [<commit_message_description>]
git_squash () {
  git reset --soft HEAD~$1
  if [ "$3" != "" ]
  then
    git commit -m "$2" -m "$3"
  else
    git commit -m "$2"
  fi
}
