#!/usr/bin/env zsh
# ~/.config/zsh/functions/git_log_with_separators

# Dependencies
## git | https://formulae.brew.sh/formula/git

# Definition
git_log_with_separators () {
  printf '─%.0s' $(seq 1 $(tput cols))
  printf '\n'
  git log "$@"
  printf '─%.0s' $(seq 1 $(tput cols))
  printf '\n'
}
