#!/usr/bin/env zsh
# ~/.config/zsh/functions/magick_pdf2image
## Dependencies:
## ImageMagick | https://formulae.brew.sh/formula/imagemagick
## Syntax:
## magick_pdf2image <input> <density> <output> [<background>]
magick_pdf2image () {
  if [ "$4" != "" ]
  then
    magick -units PixelsPerInch -density $2 $1 -background $4 -alpha remove -quality 100 $3
  else
    magick -units PixelsPerInch -density $2 $1 -alpha remove -quality 100 $3
  fi
}
