#!/usr/bin/env zsh
# ~/.config/zsh/functions/git_sanitize

# Dependencies
## git | https://formulae.brew.sh/formula/git

# Source: https://unix.stackexchange.com/a/161853

# Definition
git_sanitize () {
  git ls-files -z | while IFS= read -rd '' f; do if file --brief --mime-encoding "$f" | grep -qv binary; then tail -c1 < "$f" | read -r _ || echo >> "$f"; fi; done
}
