#!/usr/bin/env zsh
# ~/.config/zsh/functions/git_review

# Dependencies
## git | https://formulae.brew.sh/formula/git

# Definition
git_review () {
  if [[ $# -eq 0 ]] ; then
    printf '%s\n' 'No argument supplied' >&2
    return 1
  fi

  printf '─%.0s' $(seq 1 $(tput cols))
  printf '\n'

  local commit_1="$@[-2]"
  local commit_2="$@[-1]"

  git diff "${@[1,-3]}" "$commit_1" "$commit_2"

  printf '─%.0s' $(seq 1 $(tput cols))
  printf '\n'

  git diff --stat "$commit_1" "$commit_2"

  printf '─%.0s' $(seq 1 $(tput cols))
  printf '\n'
  print -Pn '%F{green}'

  git log --pretty=%B "$commit_1".."$commit_2" | head -n -1

  print -Pn '%F{reset}'
  printf '─%.0s' $(seq 1 $(tput cols))
  printf '\n'
}
