#!/usr/bin/env zsh
# ~/.config/zsh/functions/inkscape_conv

# Dependencies
## Inkscape | https://formulae.brew.sh/cask/inkscape

# Definition
inkscape_conv () {
  inkscape "$1" "${@:3}" --export-filename="$2"
}
