#!/usr/bin/env zsh
# ~/.config/zsh/functions/magick_conv
## Dependencies:
## ImageMagick | https://formulae.brew.sh/formula/imagemagick
## Syntax:
## magick_conv <input> <density> <output> [<background>]
magick_conv () {
  if [ "$4" != "" ]
  then
    magick -units PixelsPerInch -density "$2" "$1" -background "$4" -alpha remove -quality 100 "$3"
  else
    magick -units PixelsPerInch -density "$2" "$1" -alpha remove -quality 100 "$3"
  fi
}
