#!/usr/bin/env zsh
# ~/.config/zsh/functions/print_green
## Source: https://stackoverflow.com/a/77879273
print_green () {
  if [ "$1" != "-n" ]
  then
    print -P "%F{green}$@"
  else
    print -Pn "%F{green}${@:2}"
  fi
}
